In [1]:
import pandas as pd

In [9]:
df=pd.read_csv (r"/Users/Meenu/Desktop/Meenu Doc/Databases/california_housing_test.csv")

In [10]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [15]:
df['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [17]:
print(df.total_bedrooms[0])

661.0

In [6]:
#!pip install datasets

from datasets import load_dataset

ds = load_dataset("lukebarousse/data_jobs")

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (3.3.2)
Requirement already satisfied: filelock in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (19.0.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.12.0)
Requirement already satisfied: aiohttp in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (0.29.3)
Requirement already satisfied: packaging in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/Meenu/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.15.0)

/Users/Meenu/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/Meenu/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
from datasets import load_dataset

ds = load_dataset("lukebarousse/data_jobs")

In [8]:
df=ds['train'].to_pandas()

In [9]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

<Span style= "color:green; font-weight:bold; font-size:32px;" > Pracitse Prompts </span>

In [ ]:
# Problem Statement:
# Import the Pandas library under the alias pd.
# Import the load_dataset function from datasets library.
# Load the course dataset ('lukebarousse/data_jobs') using the load_dataset function.
# Transform it into a DataFrame and display the last 5 rows.

In [13]:
df.tail(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [15]:
# Problem Statement:
# Select and display the job_location column from the course dataset DataFrame you created in the last exercise 
# using bracket notation.

# Code Needed:
# import pandas as pd
# from datasets import load_dataset

# dataset = load_dataset('lukebarousse/data_jobs')
# df = dataset['train'].to_pandas()

df['job_location']

0                               Watertown, CT
1                Guadalajara, Jalisco, Mexico
2                             Berlin, Germany
3                             San Antonio, TX
4                              Washington, DC
                         ...
785736                              Singapura
785737                     Bad Rodach, Jerman
785738                               Malaysia
785739    Newark, New Jersey, Amerika Serikat
785740                                  India
Name: job_location, Length: 785741, dtype: object

In [16]:
# Problem Statement:
# Select and display the search_location column from the DataFrame using dot notation.

# Code Needed:
# import pandas as pd
# from datasets import load_dataset

# dataset = load_dataset('lukebarousse/data_jobs')
# df = dataset['train'].to_pandas()
df.search_location

0         Texas, United States
1                       Mexico
2                      Germany
3         Texas, United States
4                        Sudan
                  ...
785736               Singapore
785737                 Germany
785738                Malaysia
785739                   Sudan
785740                   India
Name: search_location, Length: 785741, dtype: object

In [18]:
# Problem Statement:
# Select the job_title from the 57th row from the DataFrame using its index.

# Code Needed:
# import pandas as pd
# from datasets import load_dataset

# dataset = load_dataset('lukebarousse/data_jobs')
# df = dataset['train'].to_pandas()

df.job_title[56]

'Principal Statistical Scientist'