In [1]:
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [3]:
df['job_country'].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [4]:
df['job_country'].isin(['Sri Lanka']).any()

np.True_

In [5]:
india_jobs=df[df['job_country']=='India']

In [7]:
india_jobs.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-06-15 13:28:03,False,False,India,None,NaN,NaN,Hexaware Technologies,"['powershell', 'python', 'sql', 'mysql', 'sql ...","{'cloud': ['databricks', 'azure'], 'databases'..."
19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,None,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,None,NaN,NaN,Exusia,None,None

In [3]:
india_jobs=df[(df['job_country']=='India')& (df['salary_year_avg'].notna())]
india_jobs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 582 entries, 1209 to 785515
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        582 non-null    object
 1   job_title              582 non-null    object
 2   job_location           582 non-null    object
 3   job_via                582 non-null    object
 4   job_schedule_type      582 non-null    object
 5   job_work_from_home     582 non-null    bool
 6   search_location        582 non-null    object
 7   job_posted_date        582 non-null    datetime64[ns]
 8   job_no_degree_mention  582 non-null    bool
 9   job_health_insurance   582 non-null    bool
 10  job_country            582 non-null    object
 11  salary_rate            582 non-null    object
 12  salary_year_avg        582 non-null    float64
 13  salary_hour_avg        0 non-null      float64
 14  company_name           582 non-null    object
 15  job_skills             551 non-null    object
 16  job_type_skills        551 non-null    object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 69.9+ KB

In [4]:
india_jobs.groupby('job_title_short').count()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,
Business Analyst,8,8,8,8,8,8,8,8,8,8,8,8,0,8,6,6
Data Analyst,94,94,94,94,94,94,94,94,94,94,94,94,0,94,86,86
Data Engineer,169,169,169,169,169,169,169,169,169,169,169,169,0,169,166,166
Data Scientist,92,92,92,92,92,92,92,92,92,92,92,92,0,92,84,84
Machine Learning Engineer,57,57,57,57,57,57,57,57,57,57,57,57,0,57,53,53
Senior Data Analyst,27,27,27,27,27,27,27,27,27,27,27,27,0,27,26,26
Senior Data Engineer,57,57,57,57,57,57,57,57,57,57,57,57,0,57,56,56
Senior Data Scientist,33,33,33,33,33,33,33,33,33,33,33,33,0,33,30,30
Software Engineer,45,45,45,45,45,45,45,45,45,45,45,45,0,45,44,44

In [5]:
india_jobs.groupby('job_title_short')[['salary_year_avg']].min()

                           salary_year_avg
job_title_short
Business Analyst                   43200.0
Data Analyst                       32400.0
Data Engineer                      43200.0
Data Scientist                     43200.0
Machine Learning Engineer          32500.0
Senior Data Analyst                64800.0
Senior Data Engineer               35000.0
Senior Data Scientist              64800.0
Software Engineer                  44418.5

In [8]:
india_jobs.groupby('job_title_short')['salary_year_avg'].agg(['min','max','median']).sort_values('median',ascending=True)

                               min       max    median
job_title_short
Business Analyst           43200.0  142025.0   64800.0
Machine Learning Engineer  32500.0  267000.0   79200.0
Software Engineer          44418.5  200000.0   79200.0
Data Analyst               32400.0  650000.0  100500.0
Senior Data Analyst        64800.0  177283.0  111175.0
Data Scientist             43200.0  204381.0  114008.0
Senior Data Engineer       35000.0  181765.0  147500.0
Data Engineer              43200.0  249000.0  147500.0
Senior Data Scientist      64800.0  170575.0  149653.0