In [1]:
!pip list

Package                           Version
--------------------------------- --------------
aiohappyeyeballs                  2.6.1
aiohttp                           3.11.13
aiosignal                         1.3.2
altgraph                          0.17.2
anyio                             4.8.0
appnope                           0.1.4
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asttokens                         3.0.0
async-lru                         2.0.4
async-timeout                     5.0.1
attrs                             25.1.0
babel                             2.17.0
beautifulsoup4                    4.13.3
bleach                            6.2.0
certifi                           2025.1.31
cffi                              1.17.1
charset-normalizer                3.4.1
comm                              0.2.2
contourpy                         1.3.0
cycler                            0.12.1
datasets                          3.3.2
debugpy                           1.8.13
decorator                         5.2.1
defusedxml                        0.7.1
dill                              0.3.8
exceptiongroup                    1.2.2
executing                         2.2.0
fastjsonschema                    2.21.1
filelock                          3.18.0
fonttools                         4.56.0
fqdn                              1.5.1
frozenlist                        1.5.0
fsspec                            2024.12.0
future                            0.18.2
greenlet                          3.1.1
h11                               0.14.0
httpcore                          1.0.7
httpx                             0.28.1
huggingface-hub                   0.29.3
idna                              3.10
importlib_metadata                8.6.1
importlib_resources               6.5.2
ipykernel                         6.29.5
ipython                           8.18.1
ipython-genutils                  0.2.0
ipywidgets                        8.1.5
isoduration                       20.11.0
jedi                              0.19.2
Jinja2                            3.1.5
json5                             0.10.0
jsonpointer                       3.0.0
jsonschema                        4.23.0
jsonschema-specifications         2024.10.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter-contrib-core              0.4.2
jupyter-contrib-nbextensions      0.7.0
jupyter_core                      5.7.2
jupyter-events                    0.12.0
jupyter-highlight-selected-word   0.2.0
jupyter-lsp                       2.2.5
jupyter_nbextensions_configurator 0.6.4
jupyter_server                    2.15.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.3.5
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
kiwisolver                        1.4.7
lxml                              5.3.1
macholib                          1.15.2
MarkupSafe                        3.0.2
matplotlib                        3.9.4
matplotlib-inline                 0.1.7
mistune                           3.1.2
multidict                         6.1.0
multiprocess                      0.70.16
mysql-connector-python            9.2.0
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest-asyncio                      1.6.0
notebook                          7.3.2
notebook_shim                     0.2.4
numpy                             2.0.2
overrides                         7.7.0
packaging                         24.2
pandas                            2.2.3
pandocfilters                     1.5.1
parso                             0.8.4
pexpect                           4.9.0
pillow                            11.1.0
pip                               25.0.1
platformdirs                      4.3.6
prometheus_client                 0.21.1
prompt_toolkit                    3.0.50
propcache                         0.3.0
psutil                            7.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
pyarrow                           19.0.1
pycparser                         2.22
Pygments                          2.19.1
PyMySQL                           1.1.1
pyparsing                         3.2.1
python-dateutil                   2.9.0.post0
python-json-logger                3.2.1
pytz                              2025.1
PyYAML                            6.0.2
pyzmq                             26.2.1
referencing                       0.36.2
requests                          2.32.3
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rpds-py                           0.23.1
Send2Trash                        1.8.3
setuptools                        58.0.4
six                               1.15.0
sniffio                           1.3.1
soupsieve                         2.6
SQLAlchemy                        2.0.38
stack-data                        0.6.3
tabulate                          0.9.0
terminado                         0.18.1
tinycss2                          1.4.0
tomli                             2.2.1
tornado                           6.4.2
tqdm                              4.67.1
traitlets                         5.14.3
types-python-dateutil             2.9.0.20241206
typing_extensions                 4.12.2
tzdata                            2025.1
uri-template                      1.3.0
urllib3                           1.26.16
wcwidth                           0.2.13
webcolors                         24.11.1
webencodings                      0.5.1
websocket-client                  1.8.0
wheel                             0.37.0
widgetsnbextension                4.0.13
xxhash                            3.5.0
yarl                              1.18.3
zipp                              3.21.0

In [2]:
import pandas as pd
from datasets import load_dataset
import numpy as np
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [3]:
df.iloc[0]

job_title_short                                       Senior Data Engineer
job_title                Senior Clinical Data Engineer / Principal Clin...
job_location                                                 Watertown, CT
job_via                                                    via Work Nearby
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                       Texas, United States
job_posted_date                                        2023-06-16 13:44:15
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                           None
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                          Boehringer Ingelheim
job_skills                                                            None
job_type_skills                                                       None
Name: 0, dtype: object

In [5]:
df.iloc[0:10]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [7]:
df.iloc[0:10,5]
df.loc[0:10,'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0         None              NaN              NaN
1         None              NaN              NaN
2         None              NaN              NaN
3         None              NaN              NaN
4         None              NaN              NaN
5         None              NaN              NaN
6         None              NaN              NaN
7         None              NaN              NaN
8         None              NaN              NaN
9         None              NaN              NaN
10        None              NaN              NaN

In [10]:
df.loc[:,'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

In [15]:
# Problem Statement:
# Select and display the job_title and job_location columns for the first 5 rows of the DataFrame using the iloc method.

df.loc[0:5,['job_title','job_location','salary_hour_avg']]

,job_title,job_location,salary_hour_avg
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",NaN
1,Data Analyst,"Guadalajara, Jalisco, Mexico",NaN
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",NaN
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",NaN
4,Data Engineer- Sr Jobs,"Washington, DC",NaN
5,GCP Data Engineer,Anywhere,NaN

In [18]:
# Problem Statement:
# Retrieve the columns starting with job_title all the way to job_posted_date for rows with an index of 5 to 9. Use the loc method.
df.loc[ 5:9,'job_title':'job_posted_date']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57

In [35]:
# Problem Statement:
# Retrieve the job_title and salary_year_avg for the first 15 rows where the job_country is 'United States'. Use the iloc method.


df_us = df[df['job_country']=='United States']

df_us.loc[0:15,['job_title','salary_year_avg']]

df_us[['job_title','salary_year_avg']].iloc[0:15]

                                            job_title  salary_year_avg
0   Senior Clinical Data Engineer / Principal Clin...              NaN
3   LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...              NaN
5                                   GCP Data Engineer              NaN
6                   Senior Data Engineer  - GCP Cloud              NaN
9                                   Data Scientist II              NaN
11                                      Data Engineer              NaN
13                               Senior Data Engineer              NaN
17                             Data Science Team Lead              NaN
26                                      Data Engineer              NaN
27  Principal Data Engineer (Lead), Knowledge Grap...              NaN
30     Senior Data Engineer (Work from home Eligible)              NaN
32   Sr. Data Scientist (NLP) - Full-time / Part-time              NaN
35                        Data Engineer - Royal Canin              NaN
36                                       Data Analyst              NaN
37                     Data Engineer III - Now Hiring              NaN

In [41]:
# Problem Statement:
# Select and display the job_title, job_location, and job_posted_date columns for rows where 
# the job_posted_date is after '2023-05-01' using the loc method.


        
df.loc[df['job_posted_date'] > '2023-05-01', ['job_title', 'job_location', 'job_posted_date']]

,job_title,job_location,job_posted_date
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",2023-06-16 13:44:15
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,2023-11-07 14:01:59
...,...,...,...
785694,Data Engineer,"Graz, Austria",2023-05-07 07:07:37
785696,Senior Analytics Engineer,"Colombia, Huila, Colombia",2023-10-23 06:31:25
785698,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile",2023-08-09 06:32:00
785701,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile",2023-08-09 06:31:57
785706,Junior Data Engineer,"Lima, Peru",2023-11-08 06:34:48