In [1]:
import pandas as pd
from datasets import load_dataset
import numpy as np
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [6]:
df.sample(5,random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,None,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,None,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,None,NaN,NaN,Morgan King,None,None
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,None,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,None,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}

In [20]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()
df_copy=df_original

median_salary=df_original['salary_year_avg'].median()

median_salary

np.float64(115000.0)

In [21]:
df_original['salary_year_avg']=df_original['salary_year_avg'].fillna(median_salary)

df_original.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [24]:
df_copy.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [26]:
id(df_copy)==id(df_original)

True

In [28]:
df_original = df.copy()
df_altered = df_original.copy()

print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the two dataframes the same? ', id(df_original) == id(df_altered))

ID of df_original:                4990074016
ID of df_altered:                 4990073872
Are the two dataframes the same?  False

<span style ="color:green; font-width:bold ; font-size:32px ;" > Practise prompts </span>

In [31]:
# Problem Statement:
# Create a copy of the DataFrame and drop rows where the salary_year_avg column has missing values.
# Display the first 5 rows of the cleaned DataFrame.

import pandas as pd
from datasets import load_dataset
import numpy as np
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()
df_copy=df_original.copy()
print(len(df_original))

df_copy=df_copy.dropna(subset=['salary_year_avg'])

print(len(df_copy))

785741
22003

In [32]:
# Problem Statement:
# Create a new DataFrame that is a random sample of 10% of the original DataFrame.
# Display the first 5 rows of the sampled DataFrame.
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df_sampled = df.sample(frac=0.1)
df_sampled.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
39234,Data Scientist,Scientist,"Wellington, New Zealand",via Trabajo.org,Full-time and Temp work,False,New Zealand,2023-12-17 06:19:04,False,False,New Zealand,None,NaN,NaN,Merck,None,None
135756,Cloud Engineer,IT Infrastructure and Digitalization Engineer,Malaysia,via BeBee Malaysia,Full-time,False,Malaysia,2023-09-11 08:31:04,False,False,Malaysia,None,NaN,NaN,Robert Bosch Engineering and Business Solution...,"['sql', 'c', 'oracle', 'react', 'tableau']","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
132925,Data Analyst,"Data Analyst, Alternate Solutions Group",Canada,via BeBee Canada,Full-time,False,Canada,2023-04-15 08:13:47,False,False,Canada,None,NaN,NaN,Canadian Imperial Bank of Commerce,"['sql', 'python', 'pyspark', 'pandas', 'scikit...","{'analyst_tools': ['tableau', 'power bi', 'exc..."
112219,Senior Data Engineer,Senior Data Engineer | 資深資料工程師 (引客數據 invos Data),"Taipei City, Taiwan",via Melga,None,False,Taiwan,2023-02-22 00:34:18,True,False,Taiwan,None,NaN,NaN,麻布數據科技股份有限公司,"['python', 'sql', 'docker', 'kubernetes']","{'other': ['docker', 'kubernetes'], 'programmi..."
518056,Data Engineer,Data Engineer (6200 USD/Mes) [Remote],Anywhere,via LinkedIn,Full-time,True,Peru,2023-12-20 11:26:16,True,False,Peru,None,NaN,NaN,Listopro,"['python', 'golang', 'aws', 'redshift', 'snowf...","{'cloud': ['aws', 'redshift', 'snowflake'], 'l..."

In [33]:
# Problem Statement:
# Create a copy of the original DataFrame and fill in missing values in the salary_year_avg column with the median salary. 
# Display the first 5 rows of the altered DataFrame.

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df_copy = df.copy()
median_salary = df_copy['salary_year_avg'].median()
df_copy['salary_year_avg'] = df_copy['salary_year_avg'].fillna(median_salary)
df_copy.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,115000.0,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."